### ISSUE TITLE
Can you make clear the license?

### ISSUE THREAD

**Issue by ifraixedes** [onstagejs/studio#14]
Hi,

I know that the license of this repository is MIT, because appears inside pacakge.json, nonetheless it would be good if you can a LICENSE file and/or a note in the README, because it would be clearer.

Thanks.

**Comment by ericholiveira** [comment]
Thx for your advise. I fixed this issue with a topic on Readme.md.

**Comment by ifraixedes** [comment]
Cool, thanks.
